---
name: Rust
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  # Minimum supported Rust version (MSRV)
  ACTION_MSRV_TOOLCHAIN: 1.56.0
  # Pinned toolchain for linting
  ACTION_LINTS_TOOLCHAIN: 1.56.0

jobs:
  tests-stable:
    name: "Tests, stable toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test
      - name: cargo build (release)
        run: cargo build --release
  tests-minimum-toolchain:
    name: "Tests, minimum supported toolchain (MSRV)"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env['ACTION_MSRV_TOOLCHAIN']  }}
      - name: cargo test (release)
        run: cargo test --release
  linting:
    name: "Lints, pinned toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env['ACTION_LINTS_TOOLCHAIN']  }}
          components: rustfmt,clippy
      - name: cargo clippy (warnings)
        run: cargo clippy -- -D warnings
      - name: cargo fmt (check)
        run: cargo fmt -- --check -l
  tests-other-channels:
    name: "Tests, unstable toolchain"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        channel:
          - "beta"
          - "nightly"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.channel }}
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test
